Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Waka.Managers;
using Waka.Models;

namespace Waka.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["userId"] = PersistUser.userId;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Waka.Brokers;
using Waka.Managers;
using Waka.Models;

namespace Waka.Controllers
{
    public class PlacesController : Controller
    {
        private readonly IStorageBroker<PublicPlaces> storage;

        public PlacesController(IStorageBroker<PublicPlaces> storage)
        {
            this.storage = storage;
        }

        // GET: PublicPlaces
        public ActionResult<IEnumerable<PublicPlaces>> Index()
        {
            return View(storage.GetAll());
        }

        public ActionResult<IEnumerable<PublicPlaces>> SuggestedPlaces()
        {

            return View(storage.GetAll().Where(p=>p.Description.ToLower() == "suggestion"));
        }

        // GET: PublicPlaces/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PublicPlaces/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Name,FullAddress,Latitude,Longitude,ImageUrl,PhoneNumber,Description")] PublicPlaces publicPlaces)
        {
            if (ModelState.IsValid)
            {
                publicPlaces.Id = Guid.NewGuid();
                publicPlaces.PostedBy = PersistUser.userName;
                storage.Post(publicPlaces);
                return RedirectToAction(nameof(Index));
            }
            return View(publicPlaces);
        }

        // GET: PublicPlaces/Edit/5
        public  ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var publicPlaces = storage.GetAll();
            var onePlace = publicPlaces.Where(s => s.Id == id).FirstOrDefault();

            if (onePlace == null)
            {
                return NotFound();
            }
            return View(onePlace);
        }

        // POST: PublicPlaces/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, [Bind("Id,Name,FullAddress,Latitude,Longitude,ImageUrl,PhoneNumber,Description")] PublicPlaces publicPlaces)
        {
            if (id != publicPlaces.Id)
            {
                return NotFound();
            }

            try
            {

                var places = storage.GetAll();
                var comparePlace = storage.GetAll().Where(c => c.Id == id).FirstOrDefault();
                var placeToUpdate = places.Where(d => d.Id == id).FirstOrDefault();

                placeToUpdate.FullAddress = string.IsNullOrWhiteSpace(publicPlaces.FullAddress) ? placeToUpdate.FullAddress : publicPlaces.FullAddress;
                placeToUpdate.Name = string.IsNullOrWhiteSpace(publicPlaces.Name) ? placeToUpdate.Name : publicPlaces.Name;
                placeToUpdate.Description = string.IsNullOrWhiteSpace(publicPlaces.Description) ? placeToUpdate.Description : publicPlaces.Description;
                placeToUpdate.PhoneNumber = string.IsNullOrWhiteSpace(publicPlaces.PhoneNumber) ? placeToUpdate.PhoneNumber : publicPlaces.PhoneNumber;
                placeToUpdate.ImageUrl = string.IsNullOrWhiteSpace(publicPlaces.ImageUrl) ? placeToUpdate.ImageUrl : publicPlaces.ImageUrl;
                placeToUpdate.PostedBy = PersistUser.userName;
               

                storage.Update(placeToUpdate, comparePlace);
            }
            catch (Exception ex)
            {
                throw ex;
               
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Waka.Brokers;
using Waka.Managers;
using Waka.Models;
using Waka.ViewModels;

namespace Waka.Controllers
{
    public class UserController : Controller
    {
        private readonly IStorageBroker<User> storage;
        private readonly UserManager userManager;

        public UserController(IStorageBroker<User> storage, UserManager userManager)
        {
            this.storage = storage;
            this.userManager = userManager;
        }

        // GET: PublicPlaces

        public ActionResult<IEnumerable<User>> Index()
        {
            return View(storage.GetAll());
        }

        // GET: PublicPlaces/Details/5


        // GET: PublicPlaces/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PublicPlaces/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("UserId,UserName,Email,Password,IsSignedIn")] User user)
        {
            SignInViewModel signInViewModel = new SignInViewModel()
            {
                Email = user.Email,
                Password = user.Password
            };
            if (ModelState.IsValid)
            {
                user.UserId = Guid.NewGuid();
                user.IsSignedIn = true;
                storage.Post(user);
                PersistUser.userId = default;
                userManager.SignIn(signInViewModel);
                PersistUser.userId = user.UserId;

                return RedirectToAction("Index", "Home");
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignIn([Bind("Email,Password")] SignInViewModel model)
        {
            if (ModelState.IsValid)
            {
               var yes = userManager.SignIn(model);
                if (yes)
                {
                    var signUser = storage.GetAll().Where(a => a.Email == model.Email).FirstOrDefault();
                    PersistUser.userId = signUser.UserId;
                    PersistUser.userName = signUser.UserName;
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignOut()
        {
            var currentUserId = PersistUser.userId;
            if (currentUserId != default)
            {
                var yes = userManager.UserIsSignedIn(currentUserId);
                if (yes)
                {
                    userManager.Logout(currentUserId);
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }


        // GET: PublicPlaces/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var userToUpdate = storage.GetAll();
            var oneUser = userToUpdate.Where(s => s.UserId == id).FirstOrDefault();

            if (oneUser == null)
            {
                return NotFound();
            }
            return View(oneUser);
        }

        // POST: PublicPlaces/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, [Bind("UserId,UserName,Email,Password,IsSignedIn")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            try
            {

                var users = storage.GetAll();
                var compareUser = storage.GetAll().Where(c => c.UserId == id).FirstOrDefault();
                var userToUpdate = users.Where(d => d.UserId == id).FirstOrDefault();

                userToUpdate.UserName = string.IsNullOrWhiteSpace(user.UserName) ? userToUpdate.UserName : user.UserName;
                

                storage.Update(userToUpdate, compareUser);
            }
            catch (Exception ex)
            {
                throw ex;

            }

            return RedirectToAction(nameof(Index));
        }

        
    }
}

Views/Home/Index.cshtml
@inject UserManager userManager;
@{
    ViewData["Title"] = "Home Page";
    var currentUser = ViewData["userId"];
    string cUser = "";
    string cUserName = "";
    if (currentUser.ToString() != "00000000-0000-0000-0000-000000000000")
    {

        cUser = currentUser.ToString();
        cUserName = userManager.CurrentSignedInUser(Guid.Parse(cUser)).Email;
    }
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">

                @if (string.IsNullOrWhiteSpace(cUser))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Register</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">Login</a>
                    </li>
                }
                else if (userManager.UserIsSignedIn(Guid.Parse(cUser)))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="Index">Places</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="Create">Create Places</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" >@cUserName</a>
                    </li>
                    <li class="nav-item">
                        <form asp-controller="User" asp-action="SignOut" method="post">
                            <button class="nav-link btn btn-link" style="width:auto; color:black">Sign Out</button>
                        </form>
                    </li>

                }

            </ul>
        </div>
    </div>
</nav>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

</div>